---
name: docker
on:
  push:
  pull_request:
jobs:
  docker:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - run: docker build . -t home
      - run: docker run --rm home echo Hello
